---
# Ansible Galaxy Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Cisco IOS collection for network automation
  - name: cisco.ios
    version: ">=4.0.0"
  
  # Network common collection (required for network_cli connection)
  - name: ansible.netcommon
    version: ">=5.0.0"
  
  # Utilities collection
  - name: ansible.utils
    version: ">=2.0.0"
  
  # Additional useful collections for network automation
  - name: community.general
    version: ">=6.0.0"
